"""Base classes for simulation agents."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime

from models.schemas import (
    ExtractionResult,
    MessageTone,
    PersonEntity,
    Platform,
    ProjectEntity,
    SourceMetadata,
    TaskEntity,
)
from simulation.clock import SimClock, SimWeek
from simulation.registry import PEOPLE, PersonRecord


@dataclass
class SimMessage:
    """A message generated by an office agent."""
    text: str
    source_meta: SourceMetadata
    extraction: ExtractionResult
    resolves_tasks: list[str] = field(default_factory=list)


@dataclass
class SimState:
    """Shared mutable state tracking the simulation's progress."""
    tasks_created: dict[str, dict] = field(default_factory=dict)
    tasks_resolved: set[str] = field(default_factory=set)
    messages_ingested: int = 0
    current_week: int = 0

    def record_message(self, msg: SimMessage):
        self.messages_ingested += 1
        for task in msg.extraction.tasks:
            self.tasks_created[task.description] = {
                "assignee": task.assignee,
                "waiting_on": task.waiting_on,
                "due_date": task.due_date,
                "status": task.status,
                "project": task.project,
            }
        for resolved in msg.resolves_tasks:
            self.tasks_resolved.add(resolved)
            if resolved in self.tasks_created:
                self.tasks_created[resolved]["status"] = "done"


class BaseAgent(ABC):
    """Abstract base for all office simulation agents."""

    def __init__(self, person_key: str):
        self.person: PersonRecord = PEOPLE[person_key]
        self.person_key = person_key
        self._msg_counter = 0

    @abstractmethod
    def generate_messages(self, week: SimWeek, state: SimState) -> list[SimMessage]:
        """Produce zero or more messages for this simulation week."""
        ...

    def _make_message(
        self,
        week: SimWeek,
        text: str,
        extraction: ExtractionResult,
        platform: Platform | None = None,
        weekday: int = 1,
        hour: int = 9,
        resolves_tasks: list[str] | None = None,
    ) -> SimMessage:
        """Helper to build a SimMessage with proper source metadata."""
        self._msg_counter += 1
        msg_id = f"{self.person_key}_w{week.week_number}_{self._msg_counter}"
        ts = SimClock.date_in_week(week, weekday=weekday, hour=hour)
        plat = platform or self.person.preferred_platform

        source_meta = SourceMetadata(
            source_id=msg_id,
            platform=plat,
            sender_name=self.person.name,
            sender_email=self.person.email,
            received_at=ts,
        )
        return SimMessage(
            text=text,
            source_meta=source_meta,
            extraction=extraction,
            resolves_tasks=resolves_tasks or [],
        )

    # --- Convenience builders for ExtractionResult fields ---

    @staticmethod
    def _person(name: str, email: str | None = None, role: str | None = None) -> PersonEntity:
        return PersonEntity(name=name, email=email, role=role)

    @staticmethod
    def _project(name: str, status: str = "active", priority: str = "high") -> ProjectEntity:
        return ProjectEntity(name=name, status=status, priority=priority)

    @staticmethod
    def _task(
        description: str,
        assignee: str | None = None,
        waiting_on: str | None = None,
        due_date: str | None = None,
        priority: str = "medium",
        project: str | None = None,
        status: str = "pending",
    ) -> TaskEntity:
        return TaskEntity(
            description=description,
            assignee=assignee,
            waiting_on=waiting_on,
            due_date=due_date,
            priority=priority,
            project=project,
            status=status,
        )

    @staticmethod
    def _tone(
        urgency: float = 0.0,
        escalation: bool = False,
        temperature: str = "neutral",
        follow_up: bool = False,
        deliverable: bool = False,
        peer_progress: bool = False,
    ) -> MessageTone:
        return MessageTone(
            urgency_language=urgency,
            escalation_signals=escalation,
            emotional_temperature=temperature,
            is_follow_up=follow_up,
            references_deliverable=deliverable,
            peer_progress_mentioned=peer_progress,
        )

    @staticmethod
    def _extraction(
        people: list[PersonEntity] | None = None,
        projects: list[ProjectEntity] | None = None,
        tasks: list[TaskEntity] | None = None,
        summary: str = "",
        urls: list[str] | None = None,
        tone: MessageTone | None = None,
    ) -> ExtractionResult:
        return ExtractionResult(
            people=people or [],
            projects=projects or [],
            tasks=tasks or [],
            summary=summary,
            urls=urls or [],
            tone=tone,
        )
